---
jobs:
 - name: set-self
   public: true
   plan:
    - get: demo-pipeline
      tigger: true
    - set-pipeline: self
      file: demo-pipelines/pipeline.yml
      var_files: 
       - demo-pipelines/pipeline-config.yml

 # singular job to run our one task
 - name: run-integration-test
   plan:
    - in_parallel:
       - get: demo-pipeline
         trigger: true 
       - get: aws-db-test
    # singular task defined in the task yaml
    - task:  run-test-task
      file: demo-pipeline/tasks/task.yml
      params:
        CF_API_URL: ((development-cf-api-url))
        CF_USERNAME: ((development-cf-deploy-username))
        CF_PASSWORD: ((development-cf-deploy-password))
        CF_ORGANIZATION: ((development-cf-organization))
        CF_SPACE: ((development-cf-space))
        SERVICE_PLAN: micro-psql
        DB_TYPE: postgres
      on_failure:
        put: slack
        params:
          text: |
            :x: FAILED to pass demo pipeline integration test
            <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: ((slack-icon-url))
      on_success:
        put: slack
        params:
          text: |
            :white_check_mark: Successfully pass demo pipeline integration test
            <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: ((slack-icon-url))

resources:
# this resource is this repo 
- name: demo-pipeline
  type: git
  source:
    uri: ((demo-pipeline-url))
    branch: ((demo-pipeline-branch))
# This resource has tests for a running db service. 
- name: aws-db-test
  type: git
  source:
    uri: ((aws-db-test-git-url))
    branch: ((aws-db-test-git-branch))
# Rhis resource for posting to slack
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
